require 'colorize'
require 'open-uri'
require 'nokogiri'
require 'pry'

require_relative './best_music/album.rb'
require_relative './best_music/cli.rb'
require_relative './best_music/genre.rb'
require_relative './best_music/scraper.rb'
require_relative './best_music/version.rb'
